theme: minima
title: mujdecisy
description: personal web page
author:
  name: Safa Yasin Müjdeci
  email: mujdecisy@gmail.com
show_excerpts: false
minima:
  date_format: "%Y-%m-%d"
  social_links:
    twitter: mujdecisy
    linkedin: mujdecisy
    github: mujdecisy
